#!/usr/bin/python

import sys, csv,getopt

try:
    from termcolor import colored
except:
    raise

try:
    opts,args = getopt.getopt(sys.argv[1:], 'm:')
except:
    raise
else:
    dopts = dict(opts)

for fields in csv.reader(sys.stdin, dialect='excel-tab'):
    if '-m' in dopts:
        idxs = [ int(i) for i in dopts['-m'].split(',') ]
        print '\t'.join([ '%d:%s' % (i+1, (i+1) in idxs and colored(v, 'red') or v) for i,v in enumerate(fields) ])
    else:
        print '\t'.join([ '%d:%s' % (i+1,v) for i,v in enumerate(fields) ])
