#!/usr/bin/env python

import sys

from Bio import SeqIO

def nonzero(handle):
    for r in SeqIO.parse(handle, 'fasta'):
        if len(r.seq) > 0:
            yield r
        else:
            print >>sys.stderr, r.id

if __name__ == '__main__':
    SeqIO.write(nonzero(sys.stdin), sys.stdout, 'fasta')
