#!/usr/bin/python

if __name__ == '__main__':
    import sys,getopt

    try:
        opts, args = getopt.getopt(sys.argv[1:], 't:')
    except:
        raise
    else:
        dopts = dict(opts)
    
    sep = dopts.get('-t', ",")


    for l in sys.stdin:
        flds = l.strip().split('\t')
        if len(flds) <= 1:
            continue
        for i in flds[0].split(sep):
            for j in flds[1].split(sep):
                print '%s\t%s' % (i, j)
