#!/usr/bin/env python
# Get intersection for arbitary intersection

if __name__ == '__main__':
    import sys

    sets, keys = [], set()
    for i in sys.argv[1:]:
        s = set([ j.strip() for j in open(i) ])
        keys.update(s)
        sets.append(s)
    
    for i in keys:
        ss = [ i in s and 1 or 0 for s in sets ]
        print '%s\t%s\t%d' % (i, '\t'.join([ str(j) for j in ss ]), sum(ss))
